elements.ee = {
    color: ["#ffffff","#7B3F00","#ffff00"],
    behavior: behaviors.AI,
    reactions: {
        "oxygen": { elem2:"carbon_dioxide", chance:0.5 },
        "meat": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "cooked_meat": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "cheese": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "rotten_cheese": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "melted_cheese": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "tomato": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "sauce": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "plant": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "evergreen": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "algae": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "grass_seed": { elem2:null, chance:0.3 , func:behaviors.FEEDPIXEL},
        "wheat_seed": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "wheat": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "potato_seed": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "potato": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "corn_seed": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "corn": { elem2:null, chance:0.1 , func:behaviors.FEEDPIXEL},
        "lichen": { elem2:null, chance:0.04, func:behaviors.FEEDPIXEL },
        "flower_seed": { elem2:null, chance:0.4 , func:behaviors.FEEDPIXEL},
        "flour": { elem2:null, chance:0.1 , func:behaviors.FEEDPIXEL},
        "dough": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "bread": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "toast": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "gingerbread": { elem2:null, chance:0.15, func:behaviors.FEEDPIXEL },
        "yogurt": { elem2:null, chance:0.15, func:behaviors.FEEDPIXEL },
        "beans": { elem2:null, chance:0.15, func:behaviors.FEEDPIXEL },
        "salt": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "sugar": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "crumb": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "herb": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "salt_water": { elem2:"dirty_water", chance:0.2 },
        "sugar_water": { elem2:"dirty_water", chance:0.2 },
        "water": { elem2:"dirty_water", chance:0.2 },
        "popcorn": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "candy": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "caramel": { elem2:null, chance:0.4, func:behaviors.FEEDPIXEL },
        "lichen": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "egg": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "yolk": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "eggnog": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "milk": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "grape": { elem2:null, chance:0.25, func:behaviors.FEEDPIXEL },
        "batter": { elem2:null, chance:0.25, func:behaviors.FEEDPIXEL },
        "baked_batter": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "butter": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "melted_butter": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "lettuce": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "baked_potato": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "ice_cream": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "cream": { elem2:null, chance:0.3, func:behaviors.FEEDPIXEL },
        "pumpkin": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "pumpkin_seed": { elem2:null, chance:0.2, func:behaviors.FEEDPIXEL },
        "coffee_bean": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "coffee_ground": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "nut": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "nut_meat": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "nut_butter": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
        "jelly": { elem2:null, chance:0.1, func:behaviors.FEEDPIXEL },
    },
    egg: "rat",
    category: "e",
    temp: 37.6,
    tempHigh: 120,
    stateHigh: "rotten_meat",
    tempLow: -18,
    stateLow: "frozen_meat",
    breakInto: "meat",
    burn:80,
    burnTime:150,
    state: "solid",
    density: 1450,
    conduct: 0.25
},